///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebinarDesktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebinarDesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c06c5ae9-6272-4f10-8e1f-6fc8693d1bf4")]
    public partial class WebinarDesktopRepository : RepoGenBaseFolder
    {
        static WebinarDesktopRepository instance = new WebinarDesktopRepository();
        WebinarDesktopRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        WebinarDesktopRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the WebinarDesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("c06c5ae9-6272-4f10-8e1f-6fc8693d1bf4")]
        public static WebinarDesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebinarDesktopRepository() 
            : base("WebinarDesktopRepository", "/", null, 0, false, "c06c5ae9-6272-4f10-8e1f-6fc8693d1bf4", ".\\RepositoryImages\\WebinarDesktopRepositoryc06c5ae9.rximgres")
        {
            _rxmainframe = new WebinarDesktopRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new WebinarDesktopRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c06c5ae9-6272-4f10-8e1f-6fc8693d1bf4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("828273ac-cd0f-4ff0-b8f7-aa8a364ec41b")]
        public virtual WebinarDesktopRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("cdee6127-9570-4713-8329-419ceb60a81d")]
        public virtual WebinarDesktopRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class WebinarDesktopRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("828273ac-cd0f-4ff0-b8f7-aa8a364ec41b")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _joshowenmale0testingInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _rxbuttonexitInfo;
            RepoItemInfo _ranorexstudiodemoapplicationInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@name='RxMainFrame' and @title='Ranorex Studio Demo Application']", parentFolder, 30000, null, true, "828273ac-cd0f-4ff0-b8f7-aa8a364ec41b", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", ".//text[@accessiblename='Enter your name']", 30000, null, "a6c1c9b3-3aff-489f-b255-a641082ea25f");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", ".//button[@name='btnSubmitUserName']", 30000, null, "f7a2e8e9-7259-422a-b8e8-fa2ea6a86979");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", ".//text[@name='lblWelcomeMessage']", 30000, null, "485d8052-535b-4c14-a221-ad6d4cbbbde6");
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "03c31a18-acdc-49f7-867f-c2cbac6734f5");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//text[@accessiblename='First name']", 30000, null, "ff9c1b7e-9a35-4248-84bd-221dd910ba90");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//text[@accessiblename='Last name']", 30000, null, "32804d51-e68e-45be-81b7-bdba15d5d2e0");
                _openInfo = new RepoItemInfo(this, "Open", ".//button[@accessiblename='Open']", 30000, null, "a1f27f2d-f58f-4304-9726-4143b94b248b");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", ".//radiobutton[@name='rdbMale']", 30000, null, "3474f964-6dd7-4335-9e04-db9280ceeb60");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", ".//button[@name='btnAddPerson']", 30000, null, "a703f5af-5a6b-413f-9a30-61a7a27dfb15");
                _joshowenmale0testingInfo = new RepoItemInfo(this, "JoshOwenMale0Testing", "tabpagelist[@name='RxTabcontrol']//listitem[@accessiblename~'^JoshOwen']", 30000, null, "0a4e7489-cec8-491b-bdf1-100fd5d3c384");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", ".//text[@name='lblNumberOfPersonsNumber']", 30000, null, "4aa1990b-1d69-423a-96cf-aaa24678d24a");
                _rxbuttonexitInfo = new RepoItemInfo(this, "RxButtonExit", "button[@name='RxButtonExit']", 30000, null, "c584243c-2896-4e16-8804-b9514325060d");
                _ranorexstudiodemoapplicationInfo = new RepoItemInfo(this, "RanorexStudioDemoApplication", "titlebar[@accessiblerole='TitleBar']", 30000, null, "14d1791c-620c-4596-b3f7-2e6f02cb27d1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("828273ac-cd0f-4ff0-b8f7-aa8a364ec41b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("828273ac-cd0f-4ff0-b8f7-aa8a364ec41b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("a6c1c9b3-3aff-489f-b255-a641082ea25f")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("a6c1c9b3-3aff-489f-b255-a641082ea25f")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("f7a2e8e9-7259-422a-b8e8-fa2ea6a86979")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("f7a2e8e9-7259-422a-b8e8-fa2ea6a86979")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("485d8052-535b-4c14-a221-ad6d4cbbbde6")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("485d8052-535b-4c14-a221-ad6d4cbbbde6")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("03c31a18-acdc-49f7-867f-c2cbac6734f5")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("03c31a18-acdc-49f7-867f-c2cbac6734f5")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("ff9c1b7e-9a35-4248-84bd-221dd910ba90")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("ff9c1b7e-9a35-4248-84bd-221dd910ba90")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("32804d51-e68e-45be-81b7-bdba15d5d2e0")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("32804d51-e68e-45be-81b7-bdba15d5d2e0")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("a1f27f2d-f58f-4304-9726-4143b94b248b")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("a1f27f2d-f58f-4304-9726-4143b94b248b")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("3474f964-6dd7-4335-9e04-db9280ceeb60")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("3474f964-6dd7-4335-9e04-db9280ceeb60")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("a703f5af-5a6b-413f-9a30-61a7a27dfb15")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("a703f5af-5a6b-413f-9a30-61a7a27dfb15")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The JoshOwenMale0Testing item.
            /// </summary>
            [RepositoryItem("0a4e7489-cec8-491b-bdf1-100fd5d3c384")]
            public virtual Ranorex.ListItem JoshOwenMale0Testing
            {
                get
                {
                    return _joshowenmale0testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The JoshOwenMale0Testing item info.
            /// </summary>
            [RepositoryItemInfo("0a4e7489-cec8-491b-bdf1-100fd5d3c384")]
            public virtual RepoItemInfo JoshOwenMale0TestingInfo
            {
                get
                {
                    return _joshowenmale0testingInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("4aa1990b-1d69-423a-96cf-aaa24678d24a")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("4aa1990b-1d69-423a-96cf-aaa24678d24a")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The RxButtonExit item.
            /// </summary>
            [RepositoryItem("c584243c-2896-4e16-8804-b9514325060d")]
            public virtual Ranorex.Button RxButtonExit
            {
                get
                {
                    return _rxbuttonexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RxButtonExit item info.
            /// </summary>
            [RepositoryItemInfo("c584243c-2896-4e16-8804-b9514325060d")]
            public virtual RepoItemInfo RxButtonExitInfo
            {
                get
                {
                    return _rxbuttonexitInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioDemoApplication item.
            /// </summary>
            [RepositoryItem("14d1791c-620c-4596-b3f7-2e6f02cb27d1")]
            public virtual Ranorex.TitleBar RanorexStudioDemoApplication
            {
                get
                {
                    return _ranorexstudiodemoapplicationInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioDemoApplication item info.
            /// </summary>
            [RepositoryItemInfo("14d1791c-620c-4596-b3f7-2e6f02cb27d1")]
            public virtual RepoItemInfo RanorexStudioDemoApplicationInfo
            {
                get
                {
                    return _ranorexstudiodemoapplicationInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("cdee6127-9570-4713-8329-419ceb60a81d")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testingInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "cdee6127-9570-4713-8329-419ceb60a81d", "")
            {
                _testingInfo = new RepoItemInfo(this, "Testing", "listitem[@text='Testing']", 30000, null, "05afe437-5c79-4fe2-bd72-6c51cdcdd34b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cdee6127-9570-4713-8329-419ceb60a81d")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cdee6127-9570-4713-8329-419ceb60a81d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("05afe437-5c79-4fe2-bd72-6c51cdcdd34b")]
            public virtual Ranorex.ListItem Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("05afe437-5c79-4fe2-bd72-6c51cdcdd34b")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}